const { requestMlEndpoint } = require('./ml/transportService');
const {
  getPatientMlReadiness,
  getPatientMlPayload,
  getPatientMlPredictions,
  getPatientMlRecommendations,
  getDoctorDashboardPatientMlReadiness,
  getDoctorDashboardPatientMlPayload,
  getDoctorDashboardPatientMlPredictions,
  getDoctorDashboardPatientMlRecommendations,
  getPatientLatestMlPrediction,
  getPatientLatestMlRecommendation,
  listPatientMlPredictionHistory,
  listPatientMlRecommendationHistory,
  getPatientMlPredictionHistoryDetail,
  getPatientMlRecommendationHistoryDetail,
  getDoctorDashboardPatientLatestMlPrediction,
  getDoctorDashboardPatientLatestMlRecommendation,
  listDoctorDashboardPatientMlPredictionHistory,
  listDoctorDashboardPatientMlRecommendationHistory,
  getDoctorDashboardPatientMlPredictionHistoryDetail,
  getDoctorDashboardPatientMlRecommendationHistoryDetail,
} = require('./ml/orchestrationService');

module.exports = {
  requestMlEndpoint,
  getPatientMlReadiness,
  getPatientMlPayload,
  getPatientMlPredictions,
  getPatientMlRecommendations,
  getDoctorDashboardPatientMlReadiness,
  getDoctorDashboardPatientMlPayload,
  getDoctorDashboardPatientMlPredictions,
  getDoctorDashboardPatientMlRecommendations,
  getPatientLatestMlPrediction,
  getPatientLatestMlRecommendation,
  listPatientMlPredictionHistory,
  listPatientMlRecommendationHistory,
  getPatientMlPredictionHistoryDetail,
  getPatientMlRecommendationHistoryDetail,
  getDoctorDashboardPatientLatestMlPrediction,
  getDoctorDashboardPatientLatestMlRecommendation,
  listDoctorDashboardPatientMlPredictionHistory,
  listDoctorDashboardPatientMlRecommendationHistory,
  getDoctorDashboardPatientMlPredictionHistoryDetail,
  getDoctorDashboardPatientMlRecommendationHistoryDetail,
};
